### ISSUE TITLE
Application freezes with loading spinner

### ISSUE THREAD

**Issue by edgarss** [phongvhd93/MySurvey#7]
When pressing refresh on the second page of surveys the loading spinner never disappears and app is unusable.

**Comment by phongvhd93** [comment]
I want to confirm that this happens when network disabled then re-enable again and the user tries to refresh the list, right?

**Comment by phongvhd93** [comment]
I fixed this bug on this pull: https://github.com/phongvhd93/MySurvey/pull/9
This related to dispatchqueue was used when show and hide the spinner.

**Comment by phongvhd93** [comment]
I accidentlty press close

**Comment by edgarss** [comment]
I still see different behaviour depending on if I press refresh on second page or third page. refreshing on third page I get sent to first item with only 5 items loaded, but refreshing on second or first page it stays on the same item and nothing changes.

**Comment by phongvhd93** [comment]
So that means, when press reload, if the table has 15 items (on 3rd page), the whole 15 items must be reloaded.

**Comment by phongvhd93** [comment]
@edgarss 
Here is the pull I fixed that bug: https://github.com/phongvhd93/MySurvey/pull/10. Take a look.
